version: '3.9'

services:
  api:
    build:
      context: ./Api
    image: minha-api
    container_name: api
    ports:
      - "8081:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # ConnectionStrings
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=appdb;UID=postgres;PWD=postgres
      # ConfigSwagger
      - ConfigSwagger__User=admin
      - ConfigSwagger__Senha=admin
      # JwtSettings
      - JwtSettings__SecretKey=12315123123-7A6A-468C-92E4-B452B25267AA
      - JwtSettings__ExpiracaoHoras=5
      - JwtSettings__Emissor=CentralTask
      # ConfigBroker (RabbitMQ)
      - ConfigBroker__HostName=rabbitmq
      - ConfigBroker__Port=5672
      - ConfigBroker__UserName=guest
      - ConfigBroker__Password=guest
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    image: meu-frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

networks:
  app_network:
    external: true

volumes:
  postgres_data:
